// Package referenceapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package referenceapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CatchResponsePokeballType.
const (
	CatchResponsePokeballTypeGreatBall  CatchResponsePokeballType = "great_ball"
	CatchResponsePokeballTypeMasterBall CatchResponsePokeballType = "master_ball"
	CatchResponsePokeballTypePokeball   CatchResponsePokeballType = "pokeball"
	CatchResponsePokeballTypeUltraBall  CatchResponsePokeballType = "ultra_ball"
)

// Valid indicates whether the value is a known member of the CatchResponsePokeballType enum.
func (e CatchResponsePokeballType) Valid() bool {
	switch e {
	case CatchResponsePokeballTypeGreatBall:
		return true
	case CatchResponsePokeballTypeMasterBall:
		return true
	case CatchResponsePokeballTypePokeball:
		return true
	case CatchResponsePokeballTypeUltraBall:
		return true
	default:
		return false
	}
}

// Defines values for CreateCatchRequestPokeballType.
const (
	CreateCatchRequestPokeballTypeGreatBall  CreateCatchRequestPokeballType = "great_ball"
	CreateCatchRequestPokeballTypeMasterBall CreateCatchRequestPokeballType = "master_ball"
	CreateCatchRequestPokeballTypePokeball   CreateCatchRequestPokeballType = "pokeball"
	CreateCatchRequestPokeballTypeUltraBall  CreateCatchRequestPokeballType = "ultra_ball"
)

// Valid indicates whether the value is a known member of the CreateCatchRequestPokeballType enum.
func (e CreateCatchRequestPokeballType) Valid() bool {
	switch e {
	case CreateCatchRequestPokeballTypeGreatBall:
		return true
	case CreateCatchRequestPokeballTypeMasterBall:
		return true
	case CreateCatchRequestPokeballTypePokeball:
		return true
	case CreateCatchRequestPokeballTypeUltraBall:
		return true
	default:
		return false
	}
}

// Defines values for CreateImportRequestSource.
const (
	CreateImportRequestSourcePokeapi CreateImportRequestSource = "pokeapi"
)

// Valid indicates whether the value is a known member of the CreateImportRequestSource enum.
func (e CreateImportRequestSource) Valid() bool {
	switch e {
	case CreateImportRequestSourcePokeapi:
		return true
	default:
		return false
	}
}

// Defines values for ImportResponseSource.
const (
	ImportResponseSourcePokeapi ImportResponseSource = "pokeapi"
)

// Valid indicates whether the value is a known member of the ImportResponseSource enum.
func (e ImportResponseSource) Valid() bool {
	switch e {
	case ImportResponseSourcePokeapi:
		return true
	default:
		return false
	}
}

// Defines values for ImportResponseStatus.
const (
	Completed  ImportResponseStatus = "completed"
	Failed     ImportResponseStatus = "failed"
	Pending    ImportResponseStatus = "pending"
	Processing ImportResponseStatus = "processing"
)

// Valid indicates whether the value is a known member of the ImportResponseStatus enum.
func (e ImportResponseStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for PokemonSummaryRarity.
const (
	PokemonSummaryRarityCommon    PokemonSummaryRarity = "common"
	PokemonSummaryRarityLegendary PokemonSummaryRarity = "legendary"
	PokemonSummaryRarityMythical  PokemonSummaryRarity = "mythical"
	PokemonSummaryRarityRare      PokemonSummaryRarity = "rare"
	PokemonSummaryRarityUncommon  PokemonSummaryRarity = "uncommon"
)

// Valid indicates whether the value is a known member of the PokemonSummaryRarity enum.
func (e PokemonSummaryRarity) Valid() bool {
	switch e {
	case PokemonSummaryRarityCommon:
		return true
	case PokemonSummaryRarityLegendary:
		return true
	case PokemonSummaryRarityMythical:
		return true
	case PokemonSummaryRarityRare:
		return true
	case PokemonSummaryRarityUncommon:
		return true
	default:
		return false
	}
}

// Defines values for ListPokemonParamsRarity.
const (
	ListPokemonParamsRarityCommon    ListPokemonParamsRarity = "common"
	ListPokemonParamsRarityLegendary ListPokemonParamsRarity = "legendary"
	ListPokemonParamsRarityMythical  ListPokemonParamsRarity = "mythical"
	ListPokemonParamsRarityRare      ListPokemonParamsRarity = "rare"
	ListPokemonParamsRarityUncommon  ListPokemonParamsRarity = "uncommon"
)

// Valid indicates whether the value is a known member of the ListPokemonParamsRarity enum.
func (e ListPokemonParamsRarity) Valid() bool {
	switch e {
	case ListPokemonParamsRarityCommon:
		return true
	case ListPokemonParamsRarityLegendary:
		return true
	case ListPokemonParamsRarityMythical:
		return true
	case ListPokemonParamsRarityRare:
		return true
	case ListPokemonParamsRarityUncommon:
		return true
	default:
		return false
	}
}

// CatchResponse defines model for catch_response.
type CatchResponse struct {
	// CaughtAt When the Pokemon was caught
	CaughtAt time.Time `json:"caught_at"`

	// Id Unique identifier of the catch
	Id openapi_types.UUID `json:"id"`

	// IsShiny Whether this catch is a shiny variant
	IsShiny      bool                      `json:"is_shiny"`
	PokeballType CatchResponsePokeballType `json:"pokeball_type"`
	Pokemon      PokemonSummary            `json:"pokemon"`
}

// CatchResponsePokeballType defines model for CatchResponse.PokeballType.
type CatchResponsePokeballType string

// CreateCatchRequest defines model for create_catch_request.
type CreateCatchRequest struct {
	// PokeballType Type of Pokeball to open
	PokeballType CreateCatchRequestPokeballType `json:"pokeball_type"`
}

// CreateCatchRequestPokeballType Type of Pokeball to open
type CreateCatchRequestPokeballType string

// CreateImportRequest defines model for create_import_request.
type CreateImportRequest struct {
	// Source The data source to import from
	Source CreateImportRequestSource `json:"source"`
}

// CreateImportRequestSource The data source to import from
type CreateImportRequestSource string

// ImportResponse defines model for import_response.
type ImportResponse struct {
	// CreatedAt Timestamp when the import was created
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier of the import
	Id openapi_types.UUID `json:"id"`

	// ItemCount Number of items imported so far
	ItemCount int `json:"item_count"`

	// Source The data source being imported from
	Source ImportResponseSource `json:"source"`

	// Status Current status of the import
	Status ImportResponseStatus `json:"status"`

	// UpdatedAt Timestamp when the import was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// ImportResponseSource The data source being imported from
type ImportResponseSource string

// ImportResponseStatus Current status of the import
type ImportResponseStatus string

// PokemonListResponse defines model for pokemon_list_response.
type PokemonListResponse struct {
	Items  []PokemonSummary `json:"items"`
	Limit  int              `json:"limit"`
	Offset int              `json:"offset"`

	// Total Total number of Pokemon matching the query
	Total int `json:"total"`
}

// PokemonStats defines model for pokemon_stats.
type PokemonStats struct {
	Attack         int `json:"attack"`
	Defense        int `json:"defense"`
	Hp             int `json:"hp"`
	SpecialAttack  int `json:"special_attack"`
	SpecialDefense int `json:"special_defense"`
	Speed          int `json:"speed"`
}

// PokemonSummary defines model for pokemon_summary.
type PokemonSummary struct {
	// Id National Pokedex number
	Id int `json:"id"`

	// Name Pokemon name
	Name string `json:"name"`

	// Rarity Rarity tier
	Rarity PokemonSummaryRarity `json:"rarity"`

	// SpriteUrl URL to the Pokemon sprite image
	SpriteUrl string       `json:"sprite_url"`
	Stats     PokemonStats `json:"stats"`

	// Types Pokemon types
	Types []string `json:"types"`
}

// PokemonSummaryRarity Rarity tier
type PokemonSummaryRarity string

// ProblemDetail RFC 9457 Problem Details
type ProblemDetail struct {
	// Detail Human-readable explanation
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the problem type
	Type *string `json:"type,omitempty"`
}

// ListPokemonParams defines parameters for ListPokemon.
type ListPokemonParams struct {
	// Limit Number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Rarity Filter by rarity tier
	Rarity *ListPokemonParamsRarity `form:"rarity,omitempty" json:"rarity,omitempty"`
}

// ListPokemonParamsRarity defines parameters for ListPokemon.
type ListPokemonParamsRarity string

// CreateCatchJSONRequestBody defines body for CreateCatch for application/json ContentType.
type CreateCatchJSONRequestBody = CreateCatchRequest

// CreateImportJSONRequestBody defines body for CreateImport for application/json ContentType.
type CreateImportJSONRequestBody = CreateImportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a catch by opening a Pokeball
	// (POST /catches)
	CreateCatch(w http.ResponseWriter, r *http.Request)
	// Get a catch by ID
	// (GET /catches/{catch_id})
	GetCatch(w http.ResponseWriter, r *http.Request, catchId openapi_types.UUID)
	// Create an import job
	// (POST /imports)
	CreateImport(w http.ResponseWriter, r *http.Request)
	// Get import status
	// (GET /imports/{import_id})
	GetImport(w http.ResponseWriter, r *http.Request, importId openapi_types.UUID)
	// List imported Pokemon
	// (GET /pokemon)
	ListPokemon(w http.ResponseWriter, r *http.Request, params ListPokemonParams)
	// Get a Pokemon by Pokedex ID
	// (GET /pokemon/{pokedex_id})
	GetPokemon(w http.ResponseWriter, r *http.Request, pokedexId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create a catch by opening a Pokeball
// (POST /catches)
func (_ Unimplemented) CreateCatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a catch by ID
// (GET /catches/{catch_id})
func (_ Unimplemented) GetCatch(w http.ResponseWriter, r *http.Request, catchId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an import job
// (POST /imports)
func (_ Unimplemented) CreateImport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get import status
// (GET /imports/{import_id})
func (_ Unimplemented) GetImport(w http.ResponseWriter, r *http.Request, importId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List imported Pokemon
// (GET /pokemon)
func (_ Unimplemented) ListPokemon(w http.ResponseWriter, r *http.Request, params ListPokemonParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a Pokemon by Pokedex ID
// (GET /pokemon/{pokedex_id})
func (_ Unimplemented) GetPokemon(w http.ResponseWriter, r *http.Request, pokedexId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCatch operation middleware
func (siw *ServerInterfaceWrapper) CreateCatch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatch operation middleware
func (siw *ServerInterfaceWrapper) GetCatch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "catch_id" -------------
	var catchId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "catch_id", chi.URLParam(r, "catch_id"), &catchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "catch_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatch(w, r, catchId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateImport operation middleware
func (siw *ServerInterfaceWrapper) CreateImport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImport operation middleware
func (siw *ServerInterfaceWrapper) GetImport(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "import_id" -------------
	var importId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "import_id", chi.URLParam(r, "import_id"), &importId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "import_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImport(w, r, importId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPokemon operation middleware
func (siw *ServerInterfaceWrapper) ListPokemon(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPokemonParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "rarity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rarity", r.URL.Query(), &params.Rarity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rarity", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPokemon(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPokemon operation middleware
func (siw *ServerInterfaceWrapper) GetPokemon(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "pokedex_id" -------------
	var pokedexId int

	err = runtime.BindStyledParameterWithOptions("simple", "pokedex_id", chi.URLParam(r, "pokedex_id"), &pokedexId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pokedex_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPokemon(w, r, pokedexId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/catches", wrapper.CreateCatch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/catches/{catch_id}", wrapper.GetCatch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/imports", wrapper.CreateImport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/imports/{import_id}", wrapper.GetImport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pokemon", wrapper.ListPokemon)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pokemon/{pokedex_id}", wrapper.GetPokemon)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZ247bOBL9FYK7b2tbsmNnNnrLZpCZBoLA6HSwwAaGQUsli2mJVEiqO0bD/77gTdaF",
	"7b7kNpg3SyJZh1WnDovlO5zyquYMmJI4ucMyLaAi5mdKVFpsBciaMwn6DckyqihnpFwLXoNQFCROclJK",
	"mOC680pPbvaF2hKlHzKQqaC1nooT/N8CGFIFoDW/hoozdEsksuPxBMNXUtWlXuQTXsSLl9N4OY2XV/NF",
	"EsdJHP8PbyY456LSK+OMKJgqWgGeYHWoASdYKkHZHh8nmGZj2x8Z/dIAohkwRXMKAvHcYDGbHZhfrWL4",
	"9zKOp7B4tZsu59lySn6bv5wuly9frlbLZRzHcQ9O09AsiERuZUHZIegLVYBAqqDSYkBUIoLMcHRDBCVs",
	"4BXj7k1rZcd5CYRpMzW/hh0py639dIeBNZXeiP+AJ3gvgKite2hKJYh/qIhUIOzTpu+IzqRNYHu1jaO2",
	"+E8BOU7wP6ITqyJHqcgN28qmqog44ONxggV8aaiATFsxvvNrDXfTceKkQ64THL77DKnScFKNFraevl8a",
	"kOqJ7B15sh+1q0MNmjhrNwwpjngNGvX3cnk7f+zwgdv6WM84hFY1F+qZHpG8EWnIFQWgjCiC7ADtCWsH",
	"5YJXA4eQmob26V6f36YDENpfu7HnKZXxThaUqitagVSkqtGtFy23O6NZduZYtFbTeD6dr7RovVgmq5c/",
	"SrQslh+mWgqqbcobFnDM+6baWRx6lHRIIEOSo5yIPqT4FDTKFOxB6OUfy6gdULY/GfhWWk2wVEQ1cmz4",
	"TSMEMIXs97GPvUVgmV7J8CgFKe2DFrwSLB1yQkvIRpjcxBCmps6eScKSSIXc9O/IxJA2u4i1HuxRZNJN",
	"pN6GQinrz4KSymcnrmFe78eTTp8WFRGCmOeSVtT4v+PERZi8PM8lDMeGhyquSBmIqn6NWJtHvhiq9LGl",
	"Ga/j/KUBcehHdR4vVgE7w3gZl3jjfmst7nMh0cGVTwwFUYqk1wN3rFZBf2SQgwt2Z/Ay7LyiHox7EV5U",
	"1pBSUm7DQOKzc8KA7p8E2WDoq/jhgBQ1nng3nXwwAj5G5U2eDZnj9BPzJ3DUvCd2sqFjBl8dQfsUXIRj",
	"wEgVkHPPa/N1IIj0mqRFExREQQRVgYL50rxHilpQTpNTXtmisWHtT0GENljCHlhGTBpVB1XQlIyKrXZW",
	"8LioBVWwbUQgiT9evtMVT/cyY4cjWpH9cL+FUrVMokiQ29meqqLZNRJEypkCpmYpryK9yOv1RWQXkZEt",
	"ENtHF++I6ztDxPOcaqpMiVC3XFxHi9WstufL6WwXFN9zBD5eMc1gp5fy/gjbz70tf8JQQqoETfFmMzkJ",
	"9QhQX4pDh4/jj+OFB9MLj99XMFUE35VQbTNQhAYiefn2DXq1XP2G1nYg+t0MlHiYNfct8GdTETYVQDKy",
	"KwHB17okzGTTgAUCXGHDuEI5b1gWpB1lUhEWKpA+Xl4gATkIYGlbFR78kWH0I6cp4mlqCpoU8BOKoD+v",
	"rta+Akp5NqDwMl6GzziqygDSD4WuUoq+Z7xY9b3yniv09l5nhK9h5x3hIo7c9bFrjOx4o5JdSdj1wxcP",
	"u7fWY2NyHU20cm4uE5wpkprCwMohvmwBfgBxQ1NAFaFMEcpAaHYZXWmlwcqC0YKKs2uQKdVzo3abU2lX",
	"me65PUy7Dnm9vkA5F6481I7wuakL6gnaCX4re9W0+z5BhGX2PqM/m6szyBluIxvYxuv1BZ7gGxDSGo9n",
	"81lsaqMamK69E/xiNp/NdQYRVRiuRW5le8e2l1CdXCZPLjJdhJsi8o3rxri76n94dvDeBXsdIXVd0tTM",
	"iz5L23ywwvWQrAXbA8d+1JVowLywhanBu4jn3w9Dv7VmrA8uI6YXJJtU3zDypiwPnetmASTT7Enu8Dtu",
	"AQRkmajCH05uqusweQXSpG7hdo+MaUu3wMVAY13G8RlfuMz719N8MlDogE8u2A0paYbaoGkgr34BkPe8",
	"Taw2kw6gjHS0tZijMiLO67uD6RHp/CJt50j7l+yNKPnU2OhVfKJEd5YqNDtq2HsIpMwfoHy+1ESQCpTh",
	"xqfQxbp5ZP8TJ4/rI2jlw4lJcH9GJ9hDxsOUCvMt2H44bkbpF//09LMMkEiAagSDzDJu+QsYZ/GcKoY+",
	"0/4A1aXZxe/30srS9UH9vfBNjx8owIN25E9W4GHPMCQ3tsnyvTXY9W7+NiIc1DwvjOgz33XI6OnXI2N0",
	"54LxgMi1pHy+yg0bpt8kcy3qv6zOPZ7kXul6ZP/1sufQndM9x7O2JRmmWucvqiC93lGp1qe/ns4RbNj6",
	"Vtw5yrPEN+0cTXzr7eSTDHLSlAoni3iCK/KVVk2Fk3msnyhzT6GO0iOgyGta3wPE9f6CSLqm48eYfktL",
	"BUKfNqLXkQkZbu/sJ8Pf0Lj5mQkUblMHiOrLQT2wkzc9tmqOjW5eHcZ6jvYYG93VthP3kDo+kr1aHtlD",
	"TT6cLFZByTthOat5I/r8jBid/la+Nzp/nXqu7Yqerej8qN2hDVWvtuswRs8GcRMO+lrwrEldL6rfcCA1",
	"nbmoz1Je4XGmf1Bkb//i6s+U9v1stMKmBXjXPyqlWb1DJY2988qXqsfN8f8BAAD//0pP8XuXIgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
