// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package order

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// OrderItemRequest defines model for order_item_request.
type OrderItemRequest struct {
	Name string `json:"name"`
}

// OrderItemResponse defines model for order_item_response.
type OrderItemResponse struct {
	Name string `json:"name"`
}

// OrderRequest defines model for order_request.
type OrderRequest struct {
	CustomerId openapi_types.UUID `json:"customer_id"`
	Items      []OrderItemRequest `json:"items"`
}

// OrderResponse defines model for order_response.
type OrderResponse struct {
	CreationDate time.Time           `json:"creation_date"`
	CustomerId   openapi_types.UUID  `json:"customer_id"`
	Items        []OrderItemResponse `json:"items"`
	OrderId      string              `json:"order_id"`
	Status       OrderStatus         `json:"status"`
}

// OrderStatus defines model for order_status.
type OrderStatus = string

// OrdersResponse defines model for orders_response.
type OrdersResponse = []OrderResponse

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	// CustomerId The customer id determines the customer of orders returned
	CustomerId *openapi_types.UUID `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// Limit The limit determines the number of orders returned
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The offset determines the skipped orders
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = OrderRequest
