apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reference-service-go
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reference-service-go
  minReplicas: 3
  maxReplicas: 10