apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

metadata:
  labels:
    env: prod
    region: eu-central-1

images:
  - name: ghcr.io/monkescience/reference-service-go
    # kustomize edit set image ghcr.io/monkescience/reference-service-go:20250609-g7f8e3c1
    newTag: placeholder
