apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fullname" . }}-migrate
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Never
      containers:
        - name: migrate
          image: '{{ include "image" . }}'
          imagePullPolicy: IfNotPresent
          command:
            - ./reference-service-go
            - --migrate-only
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "fullname" . }}-config
