openapi: "3.1.1"
info:
  version: 0.1.0
  title: Status API
servers:
  - url: https://api.example.com
    description: Production
  - url: https://staging.api.example.com
    description: Staging
paths:
  /status/live:
    get:
      operationId: get_status_live
      summary: Liveness check
      description: Returns basic process information indicating the service is up.
      responses:
        "200":
          description: Service is alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/live_response"
  /status/ready:
    get:
      operationId: get_status_ready
      summary: Readiness check
      description: Returns readiness information indicating the service is ready to serve traffic.
      responses:
        "200":
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ready_response"
  /status/metrics:
    get:
      operationId: get_status_metrics
      summary: Prometheus metrics
      description: Exposes Prometheus metrics in the text exposition format.
      responses:
        "200":
          description: Metrics successfully returned
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    live_response:
      type: object
      additionalProperties: false
      properties:
        status:
          type: string
          description: Liveness status
          examples:
            - UP
        version:
          type: string
          description: Application version
        timestamp:
          type: string
          format: date-time
          description: Current server timestamp
        uptime:
          type: string
          description: Human-readable process uptime
        go_version:
          type: string
          description: Go runtime version
      required: [status, version, timestamp, uptime, go_version]
    ready_response:
      type: object
      additionalProperties: false
      properties:
        status:
          type: string
          description: Readiness status
          examples:
            - UP
        timestamp:
          type: string
          format: date-time
          description: Current server timestamp
      required: [status, timestamp]
