// Package importsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package importsapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ImportResponseStatus.
const (
	Completed  ImportResponseStatus = "completed"
	Failed     ImportResponseStatus = "failed"
	Pending    ImportResponseStatus = "pending"
	Processing ImportResponseStatus = "processing"
)

// CreateImportRequest defines model for create_import_request.
type CreateImportRequest struct {
	// Source The data source to import from
	Source string `json:"source"`
}

// ImportResponse defines model for import_response.
type ImportResponse struct {
	// CreatedAt Timestamp when the import was created
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier of the import
	Id openapi_types.UUID `json:"id"`

	// ItemCount Number of items imported so far
	ItemCount int `json:"item_count"`

	// Source The data source being imported from
	Source string `json:"source"`

	// Status Current status of the import
	Status ImportResponseStatus `json:"status"`

	// UpdatedAt Timestamp when the import was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// ImportResponseStatus Current status of the import
type ImportResponseStatus string

// ProblemDetail RFC 9457 Problem Details
type ProblemDetail struct {
	// Detail Human-readable explanation
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the problem type
	Type *string `json:"type,omitempty"`
}

// CreateImportJSONRequestBody defines body for CreateImport for application/json ContentType.
type CreateImportJSONRequestBody = CreateImportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Trigger a Pokemon data import
	// (POST /imports)
	CreateImport(w http.ResponseWriter, r *http.Request)
	// Get import status
	// (GET /imports/{import_id})
	GetImport(w http.ResponseWriter, r *http.Request, importId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Trigger a Pokemon data import
// (POST /imports)
func (_ Unimplemented) CreateImport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get import status
// (GET /imports/{import_id})
func (_ Unimplemented) GetImport(w http.ResponseWriter, r *http.Request, importId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateImport operation middleware
func (siw *ServerInterfaceWrapper) CreateImport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImport operation middleware
func (siw *ServerInterfaceWrapper) GetImport(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "import_id" -------------
	var importId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "import_id", chi.URLParam(r, "import_id"), &importId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "import_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImport(w, r, importId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/imports", wrapper.CreateImport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/imports/{import_id}", wrapper.GetImport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SW32/bNhDH/xXitrfJtpzK6aq3rUPbvBRGl75sCAJaPNlsxB8lj2mDwP/7QFK2I1tZ",
	"k6JA32SJ5H3v7sP7+h4ao6zRqMlDfQ++2aDi6bFxyAmvpbLG0bXDzwE9xQ9cCEnSaN4tnbHoSKKHuuWd",
	"xwLsg1f34E1wDcYngb5x0sZ9UMPlBpngxFlewMiwHIe1zigoAL9yZbt4yL9gzQ1yK+GqALqzCDV4clKv",
	"YbstIOqSDkVc2Ec7rDOrT9gQbAvYZ+Gt0R6fmUYuhbjmNJKKVOiJK8u+bFAz2uAulS/cs37nUUZn5dli",
	"Us4n88Xl/Kx+UdWL83+i7NY4FWOA4IQTkgrhJOcCpDhV8VHLzwGZFKhJthIdM+0DLUfxF4sSf6/KcoJn",
	"r1aTai6qCX85P59U1fn5YlFVZVmWAz0hSDEqhVBdNybokcK8D2qVdcRVvleCgnnDWu6GkspD06QmXKOL",
	"xz8VnxVKvT4EeBZDBXjiFPxplNfBOdTE8vfTguqg0tGoRTwpQdOg9/lHvFcd5t63XHYoYvCBpn7jmKZg",
	"xXcS13FPrN/+A7E7umoJh749+woOeCge3ppBQmP30zqz6lBdCyQuu9OcP7x5zV5Vi5dsmReyv9JCD8dX",
	"9bED3gXF9cQhF3zVIcOvtuOap4/DIvWl1IZYa4IWo+2R2hPXY2h+/HDBHLboUDf7+3gX8Yx98hYb2cqG",
	"maZJdDWjN/wxIt9dXi53ODZG4FB6VVajt4gkdSNK/97EPDfDuvigFHd3RzV5b4i9ebQY+cXzCtH3m6W9",
	"w2B8ZQLVq47rm2+P/JzbvmKnaG1Tt1oTBfaFgIvc4j+WF1DALTqfFZfT+bSMCRmLOg6LGl5M59N5ZIzT",
	"JvVjlvFIz9ZkP4z4JZIuRJwaifqL3ZToffNPI+6SkxhNmKclt7aTTdo4++Sjgp39xqdfHbZQwy+zgz/P",
	"enOejTvzdlgbcgHTi+x4SfFZOf9hIo4dNYUfItDX2YcmjsU2dN3d3hC3BVRl+T9qekJ+e56qozkyJkrf",
	"8k4KdihbATvqa7h0cr1GxzhbmhtURmef6Yd+XLsjYHbfV0CKbVS1xhEY3iLtSbDccYWELlI+5mjhqR4O",
	"9dMcPJIPdYIXCtBcpcGwUw3HtBQPavwN599enZBV/gSycpf9kDCHFJzeIVb9DMSOLWTI2FuknWH3Yyud",
	"4dHdjsOxdEaEpveq4DqoYUNkfT2bcSunPRXTxijYFidjnvg6/yMZ7vT5/fTkhKvtfwEAAP//VJApLRUM",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
