apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service-go
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service-go
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service-go
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: reference-service-go
        image: ghcr.io/monkescience/reference-service-go:PLACEHOLDER
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /status/live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status/ready
            port: http
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
