apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

namespace: reference-service-go

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: reference-service-go
      app.kubernetes.io/managed-by: kustomize
      # kustomize edit set label app.kubernetes.io/version=20250609-g7f8e3c1
      app.kubernetes.io/version: PLACEHOLDER

images:
  - name: ghcr.io/monkescience/reference-service-go
    # kustomize edit set image ghcr.io/monkescience/reference-service-go:20250609-g7f8e3c1
    newTag: PLACEHOLDER
