// Package instanceapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package instanceapi

import (
	"time"
)

// InstanceInfoResponse defines model for instance_info_response.
type InstanceInfoResponse struct {
	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Hostname Instance hostname
	Hostname string `json:"hostname"`

	// Timestamp Current server timestamp
	Timestamp time.Time `json:"timestamp"`

	// Uptime Human-readable process uptime
	Uptime string `json:"uptime"`

	// Version Application version
	Version string `json:"version"`
}
