// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Catch struct {
	ID               pgtype.UUID        `json:"id"`
	PokemonPokedexID int32              `json:"pokemon_pokedex_id"`
	PokeballType     string             `json:"pokeball_type"`
	IsShiny          bool               `json:"is_shiny"`
	CaughtAt         pgtype.Timestamptz `json:"caught_at"`
}

type Import struct {
	ID        pgtype.UUID        `json:"id"`
	Source    string             `json:"source"`
	Status    string             `json:"status"`
	ItemCount int32              `json:"item_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Pokemon struct {
	PokedexID      int32              `json:"pokedex_id"`
	Name           string             `json:"name"`
	Rarity         string             `json:"rarity"`
	Types          []string           `json:"types"`
	SpriteUrl      string             `json:"sprite_url"`
	Hp             int32              `json:"hp"`
	Attack         int32              `json:"attack"`
	Defense        int32              `json:"defense"`
	SpecialAttack  int32              `json:"special_attack"`
	SpecialDefense int32              `json:"special_defense"`
	Speed          int32              `json:"speed"`
	BaseExperience int32              `json:"base_experience"`
	CaptureRate    int32              `json:"capture_rate"`
	IsLegendary    bool               `json:"is_legendary"`
	IsMythical     bool               `json:"is_mythical"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
