// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPokemon = `-- name: CountPokemon :one
SELECT COUNT(*) FROM pokemon
`

func (q *Queries) CountPokemon(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemon)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPokemonByRarity = `-- name: CountPokemonByRarity :one
SELECT COUNT(*) FROM pokemon WHERE rarity = $1
`

func (q *Queries) CountPokemonByRarity(ctx context.Context, rarity string) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemonByRarity, rarity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImport = `-- name: CreateImport :exec
INSERT INTO imports (id, source, status, item_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateImportParams struct {
	ID        pgtype.UUID        `json:"id"`
	Source    string             `json:"source"`
	Status    string             `json:"status"`
	ItemCount int32              `json:"item_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) error {
	_, err := q.db.Exec(ctx, createImport,
		arg.ID,
		arg.Source,
		arg.Status,
		arg.ItemCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getImport = `-- name: GetImport :one
SELECT id, source, status, item_count, created_at, updated_at
FROM imports
WHERE id = $1
`

func (q *Queries) GetImport(ctx context.Context, id pgtype.UUID) (Import, error) {
	row := q.db.QueryRow(ctx, getImport, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPokemonByID = `-- name: GetPokemonByID :one
SELECT pokedex_id, name, rarity, types, sprite_url,
    hp, attack, defense, special_attack, special_defense, speed,
    base_experience, capture_rate, is_legendary, is_mythical,
    created_at, updated_at
FROM pokemon
WHERE pokedex_id = $1
`

func (q *Queries) GetPokemonByID(ctx context.Context, pokedexID int32) (Pokemon, error) {
	row := q.db.QueryRow(ctx, getPokemonByID, pokedexID)
	var i Pokemon
	err := row.Scan(
		&i.PokedexID,
		&i.Name,
		&i.Rarity,
		&i.Types,
		&i.SpriteUrl,
		&i.Hp,
		&i.Attack,
		&i.Defense,
		&i.SpecialAttack,
		&i.SpecialDefense,
		&i.Speed,
		&i.BaseExperience,
		&i.CaptureRate,
		&i.IsLegendary,
		&i.IsMythical,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomPokemonByRarity = `-- name: GetRandomPokemonByRarity :one
SELECT pokedex_id, name, rarity, types, sprite_url,
    hp, attack, defense, special_attack, special_defense, speed,
    base_experience, capture_rate, is_legendary, is_mythical,
    created_at, updated_at
FROM pokemon
WHERE rarity = $1
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomPokemonByRarity(ctx context.Context, rarity string) (Pokemon, error) {
	row := q.db.QueryRow(ctx, getRandomPokemonByRarity, rarity)
	var i Pokemon
	err := row.Scan(
		&i.PokedexID,
		&i.Name,
		&i.Rarity,
		&i.Types,
		&i.SpriteUrl,
		&i.Hp,
		&i.Attack,
		&i.Defense,
		&i.SpecialAttack,
		&i.SpecialDefense,
		&i.Speed,
		&i.BaseExperience,
		&i.CaptureRate,
		&i.IsLegendary,
		&i.IsMythical,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPokemon = `-- name: ListPokemon :many
SELECT pokedex_id, name, rarity, types, sprite_url,
    hp, attack, defense, special_attack, special_defense, speed,
    base_experience, capture_rate, is_legendary, is_mythical,
    created_at, updated_at
FROM pokemon
ORDER BY pokedex_id
LIMIT $1 OFFSET $2
`

type ListPokemonParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPokemon(ctx context.Context, arg ListPokemonParams) ([]Pokemon, error) {
	rows, err := q.db.Query(ctx, listPokemon, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pokemon{}
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.PokedexID,
			&i.Name,
			&i.Rarity,
			&i.Types,
			&i.SpriteUrl,
			&i.Hp,
			&i.Attack,
			&i.Defense,
			&i.SpecialAttack,
			&i.SpecialDefense,
			&i.Speed,
			&i.BaseExperience,
			&i.CaptureRate,
			&i.IsLegendary,
			&i.IsMythical,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPokemonByRarity = `-- name: ListPokemonByRarity :many
SELECT pokedex_id, name, rarity, types, sprite_url,
    hp, attack, defense, special_attack, special_defense, speed,
    base_experience, capture_rate, is_legendary, is_mythical,
    created_at, updated_at
FROM pokemon
WHERE rarity = $1
ORDER BY pokedex_id
LIMIT $2 OFFSET $3
`

type ListPokemonByRarityParams struct {
	Rarity string `json:"rarity"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPokemonByRarity(ctx context.Context, arg ListPokemonByRarityParams) ([]Pokemon, error) {
	rows, err := q.db.Query(ctx, listPokemonByRarity, arg.Rarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pokemon{}
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.PokedexID,
			&i.Name,
			&i.Rarity,
			&i.Types,
			&i.SpriteUrl,
			&i.Hp,
			&i.Attack,
			&i.Defense,
			&i.SpecialAttack,
			&i.SpecialDefense,
			&i.Speed,
			&i.BaseExperience,
			&i.CaptureRate,
			&i.IsLegendary,
			&i.IsMythical,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportStatus = `-- name: UpdateImportStatus :exec
UPDATE imports
SET status = $2, item_count = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateImportStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	ItemCount int32       `json:"item_count"`
}

func (q *Queries) UpdateImportStatus(ctx context.Context, arg UpdateImportStatusParams) error {
	_, err := q.db.Exec(ctx, updateImportStatus, arg.ID, arg.Status, arg.ItemCount)
	return err
}

const upsertPokemon = `-- name: UpsertPokemon :exec
INSERT INTO pokemon (
    pokedex_id, name, rarity, types, sprite_url,
    hp, attack, defense, special_attack, special_defense, speed,
    base_experience, capture_rate, is_legendary, is_mythical
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (pokedex_id) DO UPDATE SET
    name = EXCLUDED.name,
    rarity = EXCLUDED.rarity,
    types = EXCLUDED.types,
    sprite_url = EXCLUDED.sprite_url,
    hp = EXCLUDED.hp,
    attack = EXCLUDED.attack,
    defense = EXCLUDED.defense,
    special_attack = EXCLUDED.special_attack,
    special_defense = EXCLUDED.special_defense,
    speed = EXCLUDED.speed,
    base_experience = EXCLUDED.base_experience,
    capture_rate = EXCLUDED.capture_rate,
    is_legendary = EXCLUDED.is_legendary,
    is_mythical = EXCLUDED.is_mythical,
    updated_at = NOW()
`

type UpsertPokemonParams struct {
	PokedexID      int32    `json:"pokedex_id"`
	Name           string   `json:"name"`
	Rarity         string   `json:"rarity"`
	Types          []string `json:"types"`
	SpriteUrl      string   `json:"sprite_url"`
	Hp             int32    `json:"hp"`
	Attack         int32    `json:"attack"`
	Defense        int32    `json:"defense"`
	SpecialAttack  int32    `json:"special_attack"`
	SpecialDefense int32    `json:"special_defense"`
	Speed          int32    `json:"speed"`
	BaseExperience int32    `json:"base_experience"`
	CaptureRate    int32    `json:"capture_rate"`
	IsLegendary    bool     `json:"is_legendary"`
	IsMythical     bool     `json:"is_mythical"`
}

func (q *Queries) UpsertPokemon(ctx context.Context, arg UpsertPokemonParams) error {
	_, err := q.db.Exec(ctx, upsertPokemon,
		arg.PokedexID,
		arg.Name,
		arg.Rarity,
		arg.Types,
		arg.SpriteUrl,
		arg.Hp,
		arg.Attack,
		arg.Defense,
		arg.SpecialAttack,
		arg.SpecialDefense,
		arg.Speed,
		arg.BaseExperience,
		arg.CaptureRate,
		arg.IsLegendary,
		arg.IsMythical,
	)
	return err
}
