// Package statusapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package statusapi

import (
	"time"
)

// LiveResponse defines model for live_response.
type LiveResponse struct {
	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Status Liveness status
	Status string `json:"status"`

	// Timestamp Current server timestamp
	Timestamp time.Time `json:"timestamp"`

	// Uptime Human-readable process uptime
	Uptime string `json:"uptime"`

	// Version Application version
	Version string `json:"version"`
}

// ReadyResponse defines model for ready_response.
type ReadyResponse struct {
	// Status Readiness status
	Status string `json:"status"`

	// Timestamp Current server timestamp
	Timestamp time.Time `json:"timestamp"`
}
