// Package pokemonapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package pokemonapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OpenPokeballRequestPokeballType.
const (
	OpenPokeballRequestPokeballTypeGreatBall  OpenPokeballRequestPokeballType = "great_ball"
	OpenPokeballRequestPokeballTypeMasterBall OpenPokeballRequestPokeballType = "master_ball"
	OpenPokeballRequestPokeballTypePokeball   OpenPokeballRequestPokeballType = "pokeball"
	OpenPokeballRequestPokeballTypeUltraBall  OpenPokeballRequestPokeballType = "ultra_ball"
)

// Defines values for OpenPokeballResponsePokeballType.
const (
	OpenPokeballResponsePokeballTypeGreatBall  OpenPokeballResponsePokeballType = "great_ball"
	OpenPokeballResponsePokeballTypeMasterBall OpenPokeballResponsePokeballType = "master_ball"
	OpenPokeballResponsePokeballTypePokeball   OpenPokeballResponsePokeballType = "pokeball"
	OpenPokeballResponsePokeballTypeUltraBall  OpenPokeballResponsePokeballType = "ultra_ball"
)

// Defines values for PokemonSummaryRarity.
const (
	PokemonSummaryRarityCommon    PokemonSummaryRarity = "common"
	PokemonSummaryRarityLegendary PokemonSummaryRarity = "legendary"
	PokemonSummaryRarityMythical  PokemonSummaryRarity = "mythical"
	PokemonSummaryRarityRare      PokemonSummaryRarity = "rare"
	PokemonSummaryRarityUncommon  PokemonSummaryRarity = "uncommon"
)

// Defines values for ListPokemonParamsRarity.
const (
	ListPokemonParamsRarityCommon    ListPokemonParamsRarity = "common"
	ListPokemonParamsRarityLegendary ListPokemonParamsRarity = "legendary"
	ListPokemonParamsRarityMythical  ListPokemonParamsRarity = "mythical"
	ListPokemonParamsRarityRare      ListPokemonParamsRarity = "rare"
	ListPokemonParamsRarityUncommon  ListPokemonParamsRarity = "uncommon"
)

// OpenPokeballRequest defines model for open_pokeball_request.
type OpenPokeballRequest struct {
	// PokeballType Type of Pokeball to open
	PokeballType OpenPokeballRequestPokeballType `json:"pokeball_type"`
}

// OpenPokeballRequestPokeballType Type of Pokeball to open
type OpenPokeballRequestPokeballType string

// OpenPokeballResponse defines model for open_pokeball_response.
type OpenPokeballResponse struct {
	// CaughtAt When the Pokemon was caught
	CaughtAt time.Time `json:"caught_at"`

	// IsShiny Whether this catch is a shiny variant
	IsShiny      bool                             `json:"is_shiny"`
	PokeballType OpenPokeballResponsePokeballType `json:"pokeball_type"`
	Pokemon      PokemonSummary                   `json:"pokemon"`
}

// OpenPokeballResponsePokeballType defines model for OpenPokeballResponse.PokeballType.
type OpenPokeballResponsePokeballType string

// PokemonListResponse defines model for pokemon_list_response.
type PokemonListResponse struct {
	Items  []PokemonSummary `json:"items"`
	Limit  int              `json:"limit"`
	Offset int              `json:"offset"`

	// Total Total number of Pokemon matching the query
	Total int `json:"total"`
}

// PokemonStats defines model for pokemon_stats.
type PokemonStats struct {
	Attack         int `json:"attack"`
	Defense        int `json:"defense"`
	Hp             int `json:"hp"`
	SpecialAttack  int `json:"special_attack"`
	SpecialDefense int `json:"special_defense"`
	Speed          int `json:"speed"`
}

// PokemonSummary defines model for pokemon_summary.
type PokemonSummary struct {
	// Id National Pokedex number
	Id int `json:"id"`

	// Name Pokemon name
	Name string `json:"name"`

	// Rarity Rarity tier
	Rarity PokemonSummaryRarity `json:"rarity"`

	// SpriteUrl URL to the Pokemon sprite image
	SpriteUrl string       `json:"sprite_url"`
	Stats     PokemonStats `json:"stats"`

	// Types Pokemon types
	Types []string `json:"types"`
}

// PokemonSummaryRarity Rarity tier
type PokemonSummaryRarity string

// ProblemDetail RFC 9457 Problem Details
type ProblemDetail struct {
	// Detail Human-readable explanation
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the problem type
	Type *string `json:"type,omitempty"`
}

// ListPokemonParams defines parameters for ListPokemon.
type ListPokemonParams struct {
	// Limit Number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Rarity Filter by rarity tier
	Rarity *ListPokemonParamsRarity `form:"rarity,omitempty" json:"rarity,omitempty"`
}

// ListPokemonParamsRarity defines parameters for ListPokemon.
type ListPokemonParamsRarity string

// OpenPokeballJSONRequestBody defines body for OpenPokeball for application/json ContentType.
type OpenPokeballJSONRequestBody = OpenPokeballRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Open a Pokeball to catch a random Pokemon
	// (POST /pokeball/open)
	OpenPokeball(w http.ResponseWriter, r *http.Request)
	// List imported Pokemon
	// (GET /pokemon)
	ListPokemon(w http.ResponseWriter, r *http.Request, params ListPokemonParams)
	// Get a Pokemon by Pokedex ID
	// (GET /pokemon/{pokedex_id})
	GetPokemon(w http.ResponseWriter, r *http.Request, pokedexId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Open a Pokeball to catch a random Pokemon
// (POST /pokeball/open)
func (_ Unimplemented) OpenPokeball(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List imported Pokemon
// (GET /pokemon)
func (_ Unimplemented) ListPokemon(w http.ResponseWriter, r *http.Request, params ListPokemonParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a Pokemon by Pokedex ID
// (GET /pokemon/{pokedex_id})
func (_ Unimplemented) GetPokemon(w http.ResponseWriter, r *http.Request, pokedexId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// OpenPokeball operation middleware
func (siw *ServerInterfaceWrapper) OpenPokeball(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenPokeball(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPokemon operation middleware
func (siw *ServerInterfaceWrapper) ListPokemon(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPokemonParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "rarity" -------------

	err = runtime.BindQueryParameter("form", true, false, "rarity", r.URL.Query(), &params.Rarity)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rarity", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPokemon(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPokemon operation middleware
func (siw *ServerInterfaceWrapper) GetPokemon(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "pokedex_id" -------------
	var pokedexId int

	err = runtime.BindStyledParameterWithOptions("simple", "pokedex_id", chi.URLParam(r, "pokedex_id"), &pokedexId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pokedex_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPokemon(w, r, pokedexId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pokeball/open", wrapper.OpenPokeball)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pokemon", wrapper.ListPokemon)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pokemon/{pokedex_id}", wrapper.GetPokemon)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RXbY/bNhL+KwTvvp13pXW8d4i/5RokWSBIjXSLAg0WxlgaWcxKpEKOkjUW/u8FSb2L",
	"3pe2ab6Z8pDzcOaZmYf3PFFlpSRKMnx9z02SYwnup6pQbit1izsoiq3GLzUasn9AmgoSSkKx0apCTQIN",
	"X2dQGFzwavDpnnfb6VCh/ZCiSbSo7Ha+5teHCpnK2KYxY6SYdcsXHGVd8vWn7gS+4HuNQNtmURekoV2U",
	"YAi1X90sON5BWRUWwWD/zYJ7ENyQFnLPj8cFt7cSGtOhpcfam6vdZ0yIHxeziJhKSYPPDEkC9T6nLdA8",
	"HL/lKBnl6OJRKsm+gWHeno9vtYyX/z2LV2fx6vpiuY7jdRz/biFnSpf2ZJ4C4RmJEvns2gsuzNbkQh6C",
	"CChHzSgX1jMlOROGAXPm7CtoAXKCxV2yj9ZOqQJBWjez5P9dOR1suglcr/LRsx7/rTHja/6vqGd51FA8",
	"asy2pi5L0IcgH+wx04sM4rcYZDNEmNZFIQz9Wb4IwnL841mX6lCB1uDWhSiFI98gpMu4hy8k4R61I3yW",
	"GZzahk1JERSBCrefmazLHeq20i2zS8stIfeO7l9q1Icxqy7i5WXAzyRFPiSt8/ZqHe6HUmIIfMd7RiqA",
	"CJLbSTguL4PxSDHDJtkD41U4eHk1sXsRPtRUmAgotmEg8YN7woBOb7IRHpm+jB9PSF7xRRumPgYz4HNU",
	"rcsHU9Zw+pn1k85Z+QH8ZkfHFO8ago4puAznQEIZmGQtr92/kwkkbiHJ62Cr0qAFBfrwR/edkfCgmr6Z",
	"qNI3pFp2PzVo67DAPcoUXBmVB8pFArO22e0KITGVFoTbWgeK+NeP7+1kHk4mb85ECfvpfXOiyqyjSMO3",
	"872gvN7VBnWiJKGk80SVkT3k1eYq8oeYyLf6btnkO1J2FEUqy4Slyhlo+qb0bbS8PK/kfjTtai1Cc66r",
	"8Sd1TGfc9EtzOsP+79GVP3EsMCEtEn5zs+gb9QzQuBVPm1nKG3Z1vGjBjNLT3itYKlrtCiy3KRKIQCY/",
	"vvmJvVxd/o9tvCF77Qyth3HVnDrgXV2CPNMIKewKZHhXFSBdNfG57nIFoYhlqpZpkHVCGgKZYIhzV0xj",
	"hhplgkykKElkh3ZiuPaRiYSpJKm1szlFgDqQy3fX1xvm/2SJSicMXsWr8IgTVASQ/pIrTSwfB6btVeOg",
	"fFDE3pwMRlgjPxyIJuGsUSZDZ7BTNa13Bcjbx8Wvv1sXsTm3ji5bmXK89oHoSuLV5oov+FfUxkOOzy/O",
	"41YwQyX4mr84vzi/sCwDyl1ColZURU7wu7eCf15YGjpGXaV8zX+uUG56vdg8Q/6vUtc1m67iRkJVFSJx",
	"G6PPxss/X+OPdYDwQ+c4DhHpGt0HL+LcHZZx/N1ANFrRoQg3Ii89mamTBI3J6qJw8m71IKiGL/95HrhJ",
	"WwmAupJfoRAp66Jngbz8AUA+qG5GibJSmjBlByRH+E5AOFYxGL07/WsHmAaZqrI9xO2LBi+KPQZI+l4Y",
	"2vTPBdBQIqG2ZTiTHp0UdmPCetZItbYbhTVoxbDXGZ2k7eOTYgZ1QXy9jO0r6U6UVh1cxHYlZLMKKbUn",
	"QDG3ojoBpNHUQSRD1/FTXL8RBaFmuwPTI6UTctzNwt7xXxBE0zZ48x1rOvz8e6CkrWFDB0wnlLUc6ykd",
	"omd0X3k5uxXp8SRX3+JTqXqdI5OPKWW+Xl42ebO9vU9bj4VP++gwlTOu/BMJ6Z/8J1PhO4wZZMN2tNUP",
	"6GibmZIaE+MtUtPKrNXu0KXq6rU97vhHAAAA//8RpDiO4xMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
