// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package order

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// OrderId Order identifier string
type OrderId = string

// OrderItemRequest defines model for order_item_request.
type OrderItemRequest struct {
	Name string `json:"name"`
}

// OrderItemResponse defines model for order_item_response.
type OrderItemResponse struct {
	Name string `json:"name"`
}

// OrderRequest defines model for order_request.
type OrderRequest struct {
	// Country Two-letter ISO 3166-1 alpha-2 country code used to build the order_id
	Country    string             `json:"country"`
	CustomerId openapi_types.UUID `json:"customer_id"`
	Items      []OrderItemRequest `json:"items"`
}

// OrderResponse defines model for order_response.
type OrderResponse struct {
	CreatedAt  time.Time           `json:"created_at"`
	CustomerId openapi_types.UUID  `json:"customer_id"`
	Items      []OrderItemResponse `json:"items"`

	// OrderId Order identifier string
	OrderId OrderId     `json:"order_id"`
	Status  OrderStatus `json:"status"`
}

// OrderStatus defines model for order_status.
type OrderStatus = string

// OrdersPage Paginated list of orders with offset pagination metadata
type OrdersPage struct {
	Data []OrderResponse `json:"data"`

	// Limit Page size used for this response
	Limit *int `json:"limit,omitempty"`

	// Offset Offset used for this response
	Offset *int `json:"offset,omitempty"`

	// Total Total number of orders matching the filter
	Total *int `json:"total,omitempty"`
}

// Problem RFC 9457 Problem Details
type Problem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code for this occurrence of the problem
	Status *int `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`

	// Type An absolute URI that identifies the problem type
	Type string `json:"type"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	// CustomerId The customer id determines the customer of orders returned
	CustomerId *openapi_types.UUID `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// Limit The limit determines the number of orders returned
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The offset determines the skipped orders
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = OrderRequest
