// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package order

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all orders
	// (GET /orders)
	GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams)
	// Place a new order
	// (POST /orders)
	PostOrders(w http.ResponseWriter, r *http.Request)
	// Get information about a specific order
	// (GET /orders/{order_id})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all orders
// (GET /orders)
func (_ Unimplemented) GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place a new order
// (POST /orders)
func (_ Unimplemented) PostOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get information about a specific order
// (GET /orders/{order_id})
func (_ Unimplemented) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", r.URL.Query(), &params.CustomerId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customer_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders", wrapper.GetOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.PostOrders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{order_id}", wrapper.GetOrder)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX23LbOBL9FRR23paweRMl6i2JklizmYo30eRaXhcINiXMkgAHAJ14Xfr3LYCkJIv0",
	"bXduTyIhoHG6+/Tp5g1msqqlAGE0nt9gzTZQUfcoVQ7qkuf2OQfNFK8NlwLP8Vv7D+I5CMMLDgppo7hY",
	"Yw/Dd1rVJWg8/4r94Mdp8HEVrWbBp3+QxUvyafo5Wiymr15//OC/wl634dNPi7OfPp6R18/J+Yezl7NJ",
	"4p9FYfx+t+Hzh88vFotnZLkicfzyx4+Lz2f/PHtx9gVfeLimxoCymP719Rn54pP04iaItsS+XNyE7UO/",
	"+gP2sLmuAc9xB3jr9V4aqC4V/NqANtbfWskalOHgIiFoBfb30LuKKr2paFnKb9jDGRVUUOxhWtclWGQV",
	"/f4GxNps8Dz0fQ9XXPTvwQDG1sP2cq4gt7bdfRe7XTL7BZgZgNW1FBoeh/YIn3cL/sX/iefOuDHZCKOu",
	"hwRafZOkBJs6tHz/FkVBkpAA0bLeUBKi7hhiMgfUaMiRkShreJkjswG04+Vtui1eYg+/fo49vFyNUMOy",
	"YZQArNFGVjumH5pMaDEt8smMsDQEEmdhQlLIpiRI47BIgKYUbCxzGrNZWkxIAXYby4DQsKAkicMkg3Q6",
	"iRMXvkKqiho8x03j0A+g2MS6wO0eflBQ4Dn+2+m+Sk+7Ej0dYe7W8W7Zng462vWvuwupUvR6kOTDOPRQ",
	"vF0K78v+XURkCqiB/JKa48CGfhiRwCd+sArCue/Pff8L9vbL4SqYzKN2+TBwOTVADK/giYksZkWUTxiQ",
	"qGABifM0J2nkJ6SYBMkkS8Npyhj2cDplcTxJAjKDtCBxmFBCk9gnaZ7MwiCdQcCy3zuRXTC3x9nybunx",
	"I8zl9ow21DSPBNDtvZ8XB8V3kN7dRb3rd9Nlj+gwQe1/FloJBvYXMSoYlAcLXFzWSq4VaL1bq0vKIB+R",
	"sW6DvqzpGoYqdE7XXFgXUMm1QbJopUWjb9xskCwKDQbV7SYuBarA0JwaK6O3ie4Wn5bt+xJd8oqbUbiA",
	"NP9Pp4mFVMhsuEY7UztLXBhYg3IBcF6MtPDWuydYMtLQckTK7TISTZWBOghhRQ3bcLF2il3w0oAasXpE",
	"NRfHMerUSmYlVMPb3716gdJ4MkXn7Q60AEN5qYcpcutDA8/QpqmoIApoTrMSEHyvS9olXNfAeMGZ7T8u",
	"QJKxRikQDKyr1rUe2ZgICG0sfccu/fndEikooLVlNtTsxyntDO/uftKd++o6ytIG0NlqdY7aDW1r3eX9",
	"EVccEoGbctQpvZHKeMcB1U1VUXV9ZBk5uyMetAsD4wLRTMuyMeBiNxaxI8t7kVYcPzTh9Gica0MGbl06",
	"C2mBde53Q/Cz8yX28BUo3QL1T4KT0BVeDYLWHM9xdBKcBNgNJBuXmlYC3OO6rU3LVEe5ZY7n+DWYt+0O",
	"e0jRCozb/nUsq708I56j3G6suOgCsvtrX5YKTKOE01NuLfzagLrGXjczHml9q1j/41AUFbOURVlEEhZF",
	"JIY8INkMGJlOJgmLfFYwOnlEL916Y047hTx2d6BBDzjbyuyhmzkUtCkNnk98N0jxqqn243v7Foyp2BjG",
	"rn8cgdT/5nUNeQfxDmSdaI9CO8Tij2C5sMRuZdwxLPT9dhQXBoQjm/0E4MzR7fQXbfHeHFz0YOvquqmr",
	"iWMFqO/oqLYg4nuBdMX796cB6mVqBMxSXNGS56gbjdFBIW09PPljwbwHdQUKgVKy7XqdKLbFjmhZHgSq",
	"lnpEFM6l3qtC59RzmV//tsndf0lsW4m8xaTgN7+sH4KGIWvltZsxsYc3QHvRfCPbO4dt4ud3b/o+051s",
	"42onG9koBrdq6lhqtn8+SzOb0b8UP8/tcI0oEvCtjaX7v5OC05v+e2D7YDd7TDPjeZ++Nm1GWhFXHK6g",
	"l0rbRQ+Ucv85sm/nRjXgPYmI9mPp91fOe/m+FG0ntHMnzWRjEEWai3UJfdgtOeM/khVtCQppUCEbkf/1",
	"dJOPxWw3N3dktaecmTHSnSuZN8y9eLhRJZ7jjTG1np+e0pqfdHPPCZPV6VWAh43+vbEdbz04rNv1kzEj",
	"F9v/BgAA//8wfdg6dRUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
