// Package pokeapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package pokeapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// NamedApiResource defines model for named_api_resource.
type NamedApiResource struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

// PaginatedPokemonSpeciesSummaryList defines model for paginated_pokemon_species_summary_list.
type PaginatedPokemonSpeciesSummaryList struct {
	Count    int                `json:"count"`
	Next     *string            `json:"next,omitempty"`
	Previous *string            `json:"previous,omitempty"`
	Results  []NamedApiResource `json:"results"`
}

// PokemonDetail defines model for pokemon_detail.
type PokemonDetail struct {
	BaseExperience *int               `json:"base_experience,omitempty"`
	Id             int                `json:"id"`
	Name           string             `json:"name"`
	Sprites        PokemonSprites     `json:"sprites"`
	Stats          []PokemonStatEntry `json:"stats"`
	Types          []PokemonTypeSlot  `json:"types"`
}

// PokemonSpeciesDetail defines model for pokemon_species_detail.
type PokemonSpeciesDetail struct {
	CaptureRate *int    `json:"capture_rate,omitempty"`
	Id          int     `json:"id"`
	IsLegendary bool    `json:"is_legendary"`
	IsMythical  bool    `json:"is_mythical"`
	Name        *string `json:"name,omitempty"`
}

// PokemonSprites defines model for pokemon_sprites.
type PokemonSprites struct {
	FrontDefault *string `json:"front_default,omitempty"`
	Other        *struct {
		OfficialArtwork *SpriteSet `json:"official-artwork,omitempty"`
	} `json:"other,omitempty"`
}

// PokemonStatEntry defines model for pokemon_stat_entry.
type PokemonStatEntry struct {
	BaseStat int              `json:"base_stat"`
	Effort   *int             `json:"effort,omitempty"`
	Stat     NamedApiResource `json:"stat"`
}

// PokemonTypeSlot defines model for pokemon_type_slot.
type PokemonTypeSlot struct {
	Slot int              `json:"slot"`
	Type NamedApiResource `json:"type"`
}

// SpriteSet defines model for sprite_set.
type SpriteSet struct {
	FrontDefault *string `json:"front_default,omitempty"`
}

// ListPokemonSpeciesParams defines parameters for ListPokemonSpecies.
type ListPokemonSpeciesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListPokemonSpecies request
	ListPokemonSpecies(ctx context.Context, params *ListPokemonSpeciesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPokemonSpecies request
	GetPokemonSpecies(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPokemon request
	GetPokemon(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListPokemonSpecies(ctx context.Context, params *ListPokemonSpeciesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPokemonSpeciesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPokemonSpecies(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPokemonSpeciesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPokemon(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPokemonRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPokemonSpeciesRequest generates requests for ListPokemonSpecies
func NewListPokemonSpeciesRequest(server string, params *ListPokemonSpeciesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pokemon-species")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPokemonSpeciesRequest generates requests for GetPokemonSpecies
func NewGetPokemonSpeciesRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pokemon-species/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPokemonRequest generates requests for GetPokemon
func NewGetPokemonRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pokemon/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListPokemonSpeciesWithResponse request
	ListPokemonSpeciesWithResponse(ctx context.Context, params *ListPokemonSpeciesParams, reqEditors ...RequestEditorFn) (*ListPokemonSpeciesResponse, error)

	// GetPokemonSpeciesWithResponse request
	GetPokemonSpeciesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetPokemonSpeciesResponse, error)

	// GetPokemonWithResponse request
	GetPokemonWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetPokemonResponse, error)
}

type ListPokemonSpeciesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginatedPokemonSpeciesSummaryList
}

// Status returns HTTPResponse.Status
func (r ListPokemonSpeciesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPokemonSpeciesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPokemonSpeciesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PokemonSpeciesDetail
}

// Status returns HTTPResponse.Status
func (r GetPokemonSpeciesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPokemonSpeciesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPokemonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PokemonDetail
}

// Status returns HTTPResponse.Status
func (r GetPokemonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPokemonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListPokemonSpeciesWithResponse request returning *ListPokemonSpeciesResponse
func (c *ClientWithResponses) ListPokemonSpeciesWithResponse(ctx context.Context, params *ListPokemonSpeciesParams, reqEditors ...RequestEditorFn) (*ListPokemonSpeciesResponse, error) {
	rsp, err := c.ListPokemonSpecies(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPokemonSpeciesResponse(rsp)
}

// GetPokemonSpeciesWithResponse request returning *GetPokemonSpeciesResponse
func (c *ClientWithResponses) GetPokemonSpeciesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetPokemonSpeciesResponse, error) {
	rsp, err := c.GetPokemonSpecies(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPokemonSpeciesResponse(rsp)
}

// GetPokemonWithResponse request returning *GetPokemonResponse
func (c *ClientWithResponses) GetPokemonWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetPokemonResponse, error) {
	rsp, err := c.GetPokemon(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPokemonResponse(rsp)
}

// ParseListPokemonSpeciesResponse parses an HTTP response from a ListPokemonSpeciesWithResponse call
func ParseListPokemonSpeciesResponse(rsp *http.Response) (*ListPokemonSpeciesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPokemonSpeciesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginatedPokemonSpeciesSummaryList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPokemonSpeciesResponse parses an HTTP response from a GetPokemonSpeciesWithResponse call
func ParseGetPokemonSpeciesResponse(rsp *http.Response) (*GetPokemonSpeciesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPokemonSpeciesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PokemonSpeciesDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPokemonResponse parses an HTTP response from a GetPokemonWithResponse call
func ParseGetPokemonResponse(rsp *http.Response) (*GetPokemonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPokemonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PokemonDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
