name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  HELM_VERSION: v3.19.0 # renovate: datasource=github-releases depName=helm/helm

jobs:
  spectral:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Spectral lint
        uses: stoplightio/spectral-action@6416fd018ae38e60136775066eb3e98172143141 # v0.8.13
        with:
          file_glob: openapi/reference-api.yaml
          spectral_ruleset: openapi/spectral.ruleset.yaml

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm lint
        run: |
          helm lint chart --strict
