on:
  workflow_call:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
    secrets:
      gitops_app_private_key:
        description: 'Private key for GitOps app'
        required: true

permissions:
  id-token: write
  contents: write

env:
  REGISTRY: ghcr.io
  KUSTOMIZE_VERSION: v5.6.0 # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_REPOSITORY: ${{ github.event.repository.name }}
  VERSION: ${{ inputs.version }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: refs/tags/${{ inputs.version }}

      - name: Set up Kustomize
        run: |
          curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${{ env.KUSTOMIZE_VERSION }}/kustomize_${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Update kustomization with new image tag and version
        run: |
          # Update image tag in overlay
          cd "deployments/overlays/${{ env.ENVIRONMENT }}"
          kustomize edit set image "ghcr.io/monkescience/${{ env.GITHUB_REPOSITORY }}:${{ env.VERSION }}"
          kustomize edit add label "app.kubernetes.io/version:${{ env.VERSION }}" --without-selector --force

      - name: Generate deployment manifests
        run: |
          mkdir -p "manifests/${{ env.ENVIRONMENT }}"
          kustomize build "deployments/overlays/${{ env.ENVIRONMENT }}" > "manifests/${{ env.ENVIRONMENT }}/manifest.yaml"

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with:
          app-id: ${{ vars.GITOPS_APP_ID }}
          private-key: ${{ secrets.gitops_app_private_key }}
          owner: monkescience
          repositories: gitops

      - name: Checkout GitOps repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: monkescience/gitops
          path: gitops
          token: ${{ steps.generate-token.outputs.token }}

      - name: Update GitOps repository
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          mkdir -p "gitops/manifests/${{ env.GITHUB_REPOSITORY }}/${{ env.ENVIRONMENT }}"
          cp "manifests/${{ env.ENVIRONMENT }}/manifest.yaml" "gitops/manifests/${{ env.GITHUB_REPOSITORY }}/${{ env.ENVIRONMENT }}/"
          cd gitops

          git config user.name "${{ vars.GITOPS_APP_USER_NAME }}"
          git config user.email "${{ vars.GITOPS_APP_ID }}+${{ vars.GITOPS_APP_USER_NAME }}@users.noreply.github.com"

          git add "manifests/${{ env.GITHUB_REPOSITORY }}/${{ env.ENVIRONMENT }}/manifest.yaml"

          if git diff --cached --quiet; then
            echo "No changes to commit for ${{ env.ENVIRONMENT }}"
          else
            git commit -m "chore(${{ env.GITHUB_REPOSITORY }}): update ${{ env.ENVIRONMENT }} manifest to version ${VERSION}"
            git push
          fi
