name: Deploy to eu-central-1-prod

on:
  repository_dispatch:
    types: [ deploy-eu-central-1-prod ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      version: ${{ github.event.client_payload.version || github.ref_name }}
      environment: eu-central-1-prod
