name: Renovate

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'debug'