name: Validate Kustomize

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

env:
  KUSTOMIZE_VERSION: v5.6.0 # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - eu-central-1-dev
          - eu-central-1-prod
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Kustomize
        run: |
          curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${{ env.KUSTOMIZE_VERSION }}/kustomize_${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Validate kustomize build for ${{ matrix.environment }}
        run: |
          # Validate that kustomize build works
          if ! kustomize build "deployments/overlays/${{ matrix.environment }}" > /dev/null; then
            echo "❌ Kustomize validation failed for ${{ matrix.environment }}"
            exit 1
          fi
          echo "✅ Kustomize validation successful for ${{ matrix.environment }}"